device: cuda
model:
  attention: false
  coarse_process_steps: 0
  edge_in_dim: 7
  hidden_size: 128
  mat_param_dim: 2
  node_in_dim: 10
  node_out_dim: 3
  process_steps: 10
  sample_ratio: 0.0
  time_dim: 1
paths:
  data_dir: ./dataset/bending_signal_trainset/
  model_dir: ./trained_models/
training:
  end_noise_level: 0.01
  learning_rate: 1e-4
  num_epochs: 500
  start_noise_level: 0.08
  weight_decay: 1e-5
  with_mat_params: false
